### ISSUE TITLE
Temporal and environmental severities reversed in json output

### ISSUE THREAD

**Issue by Roang-zero1** [RedHatProductSecurity/cvss#34]
Hi,
I've discovered a problem while using an environmental severity with the cvss3 implementation:
When using the as_json() function in the latest version the temporal and environmental severities are switched.

See: https://github.com/skontar/cvss/blob/5f8e1e8f3ba557fa44d83a4e1c488f466e9b7286/cvss/cvss3.py#L474-L475

**Comment by skontar** [comment]
@mprpic FYI, as you were adding this functionality. May be worth checking if it may have caused any issues where it was used.
