### ISSUE TITLE
Interactive mode does not work for v4.0

### ISSUE THREAD

**Issue by skontar** [RedHatProductSecurity/cvss#47]
The interactive calculator mode needs to be updated to work with version 4.0.

**Comment by tjena-ansible** [comment]
I would like to contribute to this i.e. The interactive calculator mode for CVSS v4

**Comment by chrisdlangton** [comment]
@tjena-ansible  check out `parse_cvss_from_text` method in `cvss/parser.py` 

notice it is not identifying v4 yet, might be the only problem, assuming the CVSS4 class methods are keeping parity with the previous versions
