### ISSUE TITLE
Wrong result in CVSS4 cause of round result

### ISSUE THREAD

**Issue by Xsze** [RedHatProductSecurity/cvss#58]
Hello, i've found a bug with your CVSS4 results due to how python handle the round result.

ex with  CVSS:4.0/AV:P/AC:H/AT:P/PR:L/UI:P/VC:N/VI:L/VA:H/SC:N/SI:L/SA:N/E:U/CR:H/IR:H/AR:H/MAV:L/MAC:H/MAT:P/MPR:L/MUI:P/MVC:L/MVI:L/MVA:L/MSC:L/MSI:L/MSA:S/S:N/AU:N/R:U/V:D/RE:L/U:Clear

![1](https://github.com/user-attachments/assets/dfbd2b03-5baf-4493-8a40-56e00d54b0c3)
![2](https://github.com/user-attachments/assets/7903ae1c-1809-4b17-9007-10503c996ff3)

in this exemple the final score before round = 0.95

**Comment by skontar** [comment]
Hi. Just wanted to let you know that we are aware of possible slight rounding differences due to incomplete rounding requirements. We have a plan to use equivalent rounding mechanisms in both implementation and updating specification, possibly in a similar fashion as in CVSS v3.1.

**Comment by Xsze** [comment]
Hello, thank for the feed back.

In fact i've closed the issue because when doing my test I'had some inconstistancy with the result. some x.x5 are rounded up and some (with the same x.x) are rounded down. So i'ts not only the rounding that cause these problems.
And i have identify that it come from the float type of at least 2 vars. (value and step) these two produces wrong result when used.

![image](https://github.com/user-attachments/assets/a4baddb4-2eee-49d9-bb47-029bb95923fb)
value is 1.4 and score eq4 is 0.5
![image](https://github.com/user-attachments/assets/1d96c0d0-6f76-4860-9eda-2f7c79d55d12)
result due to float is 0.8999999999999999

![image](https://github.com/user-attachments/assets/3081e707-67a8-4ee3-91ba-d969ce5adcf2)
Maxseverity eq4 = 6 and step is 0.1 but the result is 0.6000000000000001
![image](https://github.com/user-attachments/assets/8d36a311-2082-432d-b878-ad40adb41095)
all of these give the final result before rounding a score of 0.9500000000000001 who will be rounded up cause of this 0.0000000000000001 added where a normal 0.95 shoud have been rounded down.

but each result your python script produce is the same as the First calculator so it's seemes they also have this problem on the official calculator so can we call it a problem then... your online calculator don't seems to have these float bugs and so is more precise than the offcial one...
