### ISSUE TITLE
Still some floating point error

### ISSUE THREAD

**Issue by Xsze** [RedHatProductSecurity/cvss#63]
Hello,

Following the last update that should fixes floating point errors, I noticed that there were still some rounding errors due to floating point residual in the python code.

Used vector : CVSS:4.0/AV:L/AC:H/AT:N/PR:N/UI:N/VC:L/VI:H/VA:L/SC:N/SI:N/SA:H/S:N/AU:N/R:I/V:C/RE:M/U:Green/MAV:A/MAC:L/MAT:N/MPR:N/MUI:N/MVC:H/MVI:N/MVA:H/MSC:H/MSI:H/MSA:H/CR:H/IR:M/AR:H/E:A

Final result : 8.5 (on python and the online Java calculator)
![image](https://github.com/user-attachments/assets/f6e2a3a4-49e4-4964-aa5a-58a0e675aeb6)

Should have been 8.6 as the final result is ,normaly , 8.55 rounded up to 8.6
Or if we look inside vars we can see the final result before rounding is 8.549999999999999 cause of floating point again so it round it to 8.5.

It seems to come from the available distance step :
![image](https://github.com/user-attachments/assets/06bec2d4-0b59-4fa6-a174-31e7001fe43d)
![image](https://github.com/user-attachments/assets/b1e0aea8-d0a9-41ff-85fc-f64ee5dac40b)

8.6-7.2 = 1.3999999999999995
8.6-7.4=1.1999999999999993

I didn't analyse the Java online calculator but as it return the same result it should be impacted as well.

**Comment by Xsze** [comment]
Here with another vector : CVSS:4.0/AV:A/AC:H/AT:P/PR:L/UI:N/VC:H/VI:H/VA:H/SC:L/SI:H/SA:N/S:N/AU:Y/R:A/V:D/RE:H/U:Red/MAV:L/MAC:L/MAT:P/MPR:H/MUI:P/MVC:N/MVI:H/MVA:L/MSC:N/MSI:L/MSA:L/CR:L/IR:L/AR:L/E:P

0.5 instead of 0.6
![image](https://github.com/user-attachments/assets/205748e3-920e-44ef-94ef-86c2581ef554)

Final result before rounding : 
0.5499999999999999 instead of 0.55

**Comment by skontar** [comment]
@Xsze thanks for reporting!

It is unfortunate, that CVSS SIG decided to use floating point arithmetic for score computations instead of fixed point arithmetic causing these issues.

Currently, the goal of this project is to match results from official implementation at https://github.com/RedHatProductSecurity/cvss-v4-calculator and https://www.first.org/cvss/calculator/4.0 (these should match). The CVSSv4.0 specification does not have any recommendation for handling of rounding the same way the v3.1 has (see Appendix A - Floating Point Rounding).

The best way to get this improved is to either contact CVSS SIG directly https://support.first.org/servicedesk/customer/portal/1/create/4 or opening an issue at https://github.com/RedHatProductSecurity/cvss-v4-calculator where some of the members are active.

**Comment by skontar** [comment]
@Xsze I see that you did a lot of investigation on this issue. Would you be able to provide test vector files with your expected values?

**Comment by Xsze** [comment]
Of course, here they are.
[vectors_base4_divergence.txt](https://github.com/user-attachments/files/17280860/vectors_base4_divergence.txt)
[vectors_random4_divergence.txt](https://github.com/user-attachments/files/17280862/vectors_random4_divergence.txt)
[vectors_modified4_divergence.txt](https://github.com/user-attachments/files/17280863/vectors_modified4_divergence.txt)

It's based on the test files you provided.

**Comment by Xsze** [comment]
If the use of floating point is mandatory, i think something like this should eliminate the problem:
 
![image](https://github.com/user-attachments/assets/3aa260da-c8fe-47b6-a2f4-182c57f5f0b7)

Just before the final rounding a pre rounding to 2 decimal to get the variable nearer to what it should be and then you do the final rounding.

CVSS:4.0/AV:N/AC:L/AT:P/PR:H/UI:A/VC:N/VI:L/VA:H/SC:N/SI:L/SA:N
![image](https://github.com/user-attachments/assets/2113b2e9-306a-41a8-b879-4e6c04c9f538)
here, the actulal method do 5.6 but with the pre rounding you get the correct 5.7 final answear.

it can be implemented easily on java too for the online calculators.
It need some more test to see if it impact anything else but for now everything seems good.

**Comment by Xsze** [comment]
If the use of floating point is mandatory, i think something like this should eliminate the problem without to mess with all the code:

```
if "9999999999999" in str(value):
     preroundedvalue = round_away_from_zero(value*10)
     self.base_score = round_away_from_zero(preroundedvalue/10)
else:
     self.base_score = round_away_from_zero(value)
```

In place of the final rounding, if the value before rounding contains 9999999999999 a pre rounding to 2 decimal is done to get the variable nearer to what it should be and then you do the final rounding. Else it does the final rounding like now.

CVSS:4.0/AV:N/AC:L/AT:P/PR:H/UI:A/VC:N/VI:L/VA:H/SC:N/SI:L/SA:N
here, the actual method give 5.6 for this vector but with the pre rounding you get the correct 5.7 final answear.

i think it can be implemented easily on java too for the online calculators.
I've test it on the 3000 first line of vector_base4 and It need some more test to see if it impact anything else but for now everything seems good.

**Comment by skontar** [comment]
I am more thinking about pre-rounding to more decimal places and then rounding to one. Checking for string of nines is really hacky. Floating points are not mandatory, but rewriting whole CVSS v4.0 algorithm to Decimals would be painful and then we could end in a situation when it could be hard to match in other implementations.

I am thinking something like (not tested yet):
```python
def final_rounding(x):
    """
    Round to one decimal place. Use Decimal because Python float rounding defaults to
    "round half to even". We actually want "round half away from zero" aka "round half up" for
    positive numbers.

    Make sure that values like the following are correctly rounded despite flouting point
    inaccuracies:

    8.6 - 7.15 = 1.4499999999999993 (float) ➔ 1.5
    """
    pre_rounded = D(x).quantize(D("0.001"), rounding=ROUND_HALF_UP)
    return float(D(pre_rounded).quantize(D("0.1"), rounding=ROUND_HALF_UP))
```

**Comment by skontar** [comment]
@Xsze Looking at the files you posted, would you be able to easily generate test vectors like they are in the project, but with "fixed" values (so they are drop in replacements)?

**Comment by Xsze** [comment]
It's hacky but it works 👍 Tested it on 75% of base 4 and Random4 files and 50% of the modified4 and no errors show up.

I have already tested something as you propose but with a pre rounding to 0.01 first on every result and it corrected the said wrong results but it introduced a lot more new one, that's why i go the if 999999 route to limit the scope of the pre rounding to just the important one. So maybe with a wider pre rounding to 0.001 like you propose or even 0.0001 to reduce the risk to interfer with the good result it might work.

Anyway, here are the file requested.
[vectors_random4_NewOutput.txt](https://github.com/user-attachments/files/17350402/vectors_random4_NewOutput.txt)
[vectors_base4_NewOutput.txt](https://github.com/user-attachments/files/17350401/vectors_base4_NewOutput.txt)
[vectors_modified4_NewOutput_Part1.txt](https://github.com/user-attachments/files/17350416/vectors_modified4_NewOutput_Part1.txt)
[vectors_modified4_NewOutput_Part2.txt](https://github.com/user-attachments/files/17350417/vectors_modified4_NewOutput_Part2.txt)

**Comment by skontar** [comment]
@Xsze please check #65 . Looks like it is working as expected.

**Comment by Xsze** [comment]
Just tested with Base and Random and all seems good to me.

Now, it only remains to apply the correction to the online calculator.

**Comment by skontar** [comment]
I have another colleague to check that, test and fix, next week. Until then, I will keep the PR blocked, so we can do it at once.

**Comment by skontar** [comment]
@Xsze after discussion with CVSS SIG members we opted for different, simpler fix. Would you mind verifying the following implementations?
https://github.com/RedHatProductSecurity/cvss-v4-calculator/pull/67
https://github.com/RedHatProductSecurity/cvss/pull/65

**Comment by Xsze** [comment]
Seems still good to me.

**Comment by skontar** [comment]
@Xsze thank you very much for your contributions and patience.
